apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UuY2prY2V3NG1zZmx3LmFwLXNvdXRoLTIucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: c3VyeWFtdXJhbGk=

